name: pull-request
on:
  pull_request:
    types: [opened, synchronize]
  merge_group:

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/bun-verify.yml@v2
    with:
      os: '["ubuntu-latest"]'
      skip-playwright: true

  changeset:
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' && !startsWith(github.head_ref, 'changeset-release/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - name: Check for changeset
        run: bunx changeset status --since=origin/main
