name: release
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  code:
    uses: unional/.github/.github/workflows/bun-verify.yml@main
    with:
      os: '["ubuntu-latest"]'

  release:
    uses: unional/.github/.github/workflows/bun-release-changeset.yml@main
    needs: code
    secrets: inherit
